name: Build Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build:prod
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/iitc_plugin_Refresh.user.js'
          default_author: github_actions
          message: 'Release Version Update'
